config/routes.rb
 Rails.application.routes.draw do

  namespace :admin do
    resources :entry_points, only: [:index]
    resources :panels
    resources :event_questions
    resources :visitor_questions
    # resources :ratings
    # resources :rating_schemas
    # resources :rating_sessions
    resources :rating_steps, only: [:create, :edit, :update]

    root to: "entry_points#index"
  end

  root to: 'visitor/panels#index'

  namespace :interviewer do
    get 'main', to: 'main#index', as: 'main_index'

    resources :rating_sessions, only: [:new, :create]

    resources :panels, only: [:index] do
      resources :questions, only: [:new, :create]
    end
  end

  namespace :redakteur do
    resources :panels, only: [:show] do
      put 'update_question', on: :collection
      resources :selected_questions, only: [:create, :update, :destroy]
    end
  end

  namespace :moderator do
    get  'panels-zfm-16-55/:id(.:format)', to: 'panels#show', as: 'panel'
    post 'panels-zfm-16-55/:panel_id/current_questions', to: 'current_questions#create', as: 'panel_current_questions'
    delete 'panels-zfm-16-55/:panel_id/current_questions/:id', to: 'current_questions#destroy', as: 'panel_current_question'

    # resources :panels, only: [:show] do
    #   resources :current_questions, only: [:create, :destroy]
    # end
  end

  namespace :playout do
    resources :panels, only: [:show]
  end

  namespace :operator do
    resources :panels, only: [:index] do
      resources :questions, only: [:new, :create]
    end
  end

  namespace :visitor do
    resources :panels, only: [:index] do
      resources :questions, only: [:new, :create]
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admin/main_controller.rb
class Admin::MainController < ApplicationController

  def index
  end

end

app/controllers/interviewer/main_controller.rb
class Interviewer::MainController < ApplicationController

  def index
  end

end

app/controllers/interviewer/panels_controller.rb
class Interviewer::PanelsController < ApplicationController

  def index
    @panels = Panel.order('id asc')
  end

end

app/controllers/interviewer/questions_controller.rb
class Interviewer::QuestionsController < ApplicationController

  def new
    @panel = Panel.find(params[:panel_id])
    @question = VisitorQuestion.new
  end

  def create
    @panel = Panel.find(question_params[:panel_id])
    @question = @panel.questions.create!(
      type: 'VisitorQuestion',
      content: question_params[:content],
      author: 'visitor'
    )

    VisitorQuestionsRelayJob.perform_later(@panel, @question)
    GlobalVisitorQuestionsRelayJob.perform_later(@panel, @question)

    redirect_to interviewer_main_index_url, notice: "Die Frage wurde gespeichert."
  end

private
  def question_params
    params.permit(:panel_id, :content)
  end

end

app/controllers/interviewer/rating_sessions_controller.rb
class Interviewer::RatingSessionsController < ApplicationController

  def new
    scope = EventQuestion.order('id asc')
    if params[:p] == '0'
      @questions = scope.where(prefix: nil)
    elsif params[:p] == '1'
      @questions = scope.where.not(prefix: nil)
    else
      @questions = scope.all
    end
  end

  def create
    # filter checked rating params
    checked_ratings_params = []

    rating_session_params[:ratings].each do |pos, rating_params|
      if rating_params[:rating_step_id]
        checked_ratings_params << {
          question_id: rating_params[:question_id],
          rating_step_id: rating_params[:rating_step_id]
        }
      end
    end

    if checked_ratings_params.any?

      ActiveRecord::Base.transaction do
        rating_session = RatingSession.create!(
          feedback: rating_session_params[:feedback]
        )
        checked_ratings_params.each do |row|
          rating_session.ratings.create!(
            question_id: row[:question_id],
            rating_step_id: row[:rating_step_id]
          )
        end
      end # transaction

      Panel.all.each do |panel|
        RatingsRelayJob.perform_later(panel)
      end

    end # if

    redirect_to interviewer_main_index_url, notice: "Die Befragung wurde gespeichert"
  end

private
  def rating_session_params
    params.require(:rating_session).permit(:feedback, ratings: [:question_id, :rating_step_id])
  end

end

app/views/interviewer/main/index.html.erb
  <% page_title('Befrager - Startscreen') %>
  <% provide(:extra_body_attributes, raw("data-channels=\"GlobalVisitorQuestionsChannel\"")) %>

  <div class="container-flex">

    <div class="section app-left-side">
      <div class="app-inline-container">

        <h3 class="push-20">Anzahl Bewertungen</h3>
        <div class="row push-70">
            <div class="col-md-4 col-md-offset-4">

                <div class="block-content widget-question-counter clearfix">
                    <div class="pull-right push-15-t push-15">
                        <i class="fa fa-clipboard-list fa-2x text-smooth"></i>
                    </div>
                    <div class="h2 push-15-t text-left" id="rating-count"><%= Rating.count %></div>
                    <div class="text-uppercase text-left tx-15">Gesamt</div>
                </div>
            </div>
        </div>

        <h1 class="push-30">Umfrage</h1>
        <h3 class="push-50">Startet den offiziellen Fragebogen des Veranstalters.</h3>

        <%= link_to new_interviewer_rating_session_path, class: 'btn btn-success btn-with-icon push-10-l' do %>
          <div class="ht-40 justify-content-between" style="float:left;">
            <span class="pd-x-15">Umfrage starten</span>
            <span class="icon wd-40"><i class="fa fa-clipboard-list"></i></span>
          </div>
        <%- end -%>
      </div>
    </div>

    <div class="section app-right-side center">

      <div class="app-inline-container">
        <h3 class="push-20">Anzahl Teilnehmerfragen</h3>
        <div class="row push-70">
          <% Panel.order(:id).each do |panel| %>
          <div class="col-md-4">

            <div class="block-content widget-panel-<%= panel.id %> clearfix">
              <div class="pull-right push-15-t push-15">
                <i class="fa fa-users fa-2x text-smooth"></i>
              </div>
              <div id="panel-question-count-<%= panel.id %>" class="h2 push-15-t text-left"><%= panel.questions.count %></div>
              <div class="text-uppercase text-left tx-15">Panel <%= panel.id %></div>
            </div>
          </div>
          <% end %>
        </div>

        <h1 class="push-30">Teilnehmerfragen</h1>
        <h3 class="push-50">Erfassen Sie eine Teilnehmerfrage.</h3>

        <%= link_to interviewer_panels_path, class: 'btn btn-success btn-with-icon push-10-l' do %>
          <div class="ht-40 justify-content-between">
            <span class="pd-x-15">Teilnehmerfrage erfassen</span>
            <span class="icon wd-40"><i class="fa fa-comment-alt"></i></span>
          </div>
        <%- end -%>

      </div>
    </div>

  </div>