config/routes.rb
 Rails.application.routes.draw do

  namespace :admin do
    resources :entry_points, only: [:index]
    resources :panels
    resources :event_questions
    resources :visitor_questions
    # resources :ratings
    # resources :rating_schemas
    # resources :rating_sessions
    resources :rating_steps, only: [:create, :edit, :update]

    root to: "entry_points#index"
  end

  root to: 'visitor/panels#index'

  namespace :interviewer do
    get 'main', to: 'main#index', as: 'main_index'

    resources :rating_sessions, only: [:new, :create]

    resources :panels, only: [:index] do
      resources :questions, only: [:new, :create]
    end
  end

  namespace :redakteur do
    resources :panels, only: [:show] do
      put 'update_question', on: :collection
      resources :selected_questions, only: [:create, :update, :destroy]
    end
  end

  namespace :moderator do
    get  'panels-zfm-16-55/:id(.:format)', to: 'panels#show', as: 'panel'
    post 'panels-zfm-16-55/:panel_id/current_questions', to: 'current_questions#create', as: 'panel_current_questions'
    delete 'panels-zfm-16-55/:panel_id/current_questions/:id', to: 'current_questions#destroy', as: 'panel_current_question'

    # resources :panels, only: [:show] do
    #   resources :current_questions, only: [:create, :destroy]
    # end
  end

  namespace :playout do
    resources :panels, only: [:show]
  end

  namespace :operator do
    resources :panels, only: [:index] do
      resources :questions, only: [:new, :create]
    end
  end

  namespace :visitor do
    resources :panels, only: [:index] do
      resources :questions, only: [:new, :create]
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :panel, optional: true
  belongs_to :rating_schema, optional: true

  has_many :ratings, dependent: :destroy

  after_destroy do |question|
    Panel.all.each { |panel| panel.cleanup_question_references! }
  end

  def highest_rating_step
    if rating_schema
      rating_schema.rating_steps.sort_by(&:value).last
    end
  end

  def highest_rating_count
    if rating_schema
      ratings.where(rating_step: highest_rating_step).count
    end
  end

  def overall_rating_count
    if rating_schema
      ratings.count
    end
  end

  def rating_stats
    stats = self.class.empty_rating_stats

    if rating_schema
      overall_count = ratings.count
      step_counts = rating_schema.rating_steps.map { |rating_step| ratings.where(rating_step_id: rating_step.id).count }
      max_step_count = step_counts.max

      if max_step_count > 0
        stats[:overall_rating_count] = overall_count
        stats[:max_step_count] = max_step_count

        rating_schema.rating_steps.each_with_index do |rating_step, i|
          step_count = step_counts[i]
          stats[:rating_step_counts] << { name: rating_step.name, count: step_count, max_count: max_step_count, percent: ((step_count.to_f / max_step_count.to_f) * 100.0).round }
        end
      end
    end

    stats
  end

  def self.empty_rating_stats
    { rating_step_counts: [] }
  end

  # scopes
  # ----

  def self.recent
    order('created_at desc')
  end

end

app/controllers/interviewer/questions_controller.rb
class Interviewer::QuestionsController < ApplicationController

  def new
    @panel = Panel.find(params[:panel_id])
    @question = VisitorQuestion.new
  end

  def create
    @panel = Panel.find(question_params[:panel_id])
    @question = @panel.questions.create!(
      type: 'VisitorQuestion',
      content: question_params[:content],
      author: 'visitor'
    )

    VisitorQuestionsRelayJob.perform_later(@panel, @question)
    GlobalVisitorQuestionsRelayJob.perform_later(@panel, @question)

    redirect_to interviewer_main_index_url, notice: "Die Frage wurde gespeichert."
  end

private
  def question_params
    params.permit(:panel_id, :content)
  end

end

app/controllers/operator/panels_controller.rb
class Operator::PanelsController < ApplicationController

  def index
    @panels = Panel.order('id asc')
  end

end

app/controllers/operator/questions_controller.rb
class Operator::QuestionsController < ApplicationController

  def new
    @panel = Panel.find(params[:panel_id])
    @question = VisitorQuestion.new
  end

  def create
    @panel = Panel.find(question_params[:panel_id])
    @question = @panel.questions.create!(
      type: 'VisitorQuestion',
      content: question_params[:content],
      author: 'operator'
    )

    VisitorQuestionsRelayJob.perform_later(@panel, @question)
    GlobalVisitorQuestionsRelayJob.perform_later(@panel, @question)

    redirect_to operator_panels_url, notice: "Die Frage wurde gespeichert."
  end

private
  def question_params
    params.permit(:panel_id, :content)
  end

end

app/controllers/visitor/questions_controller.rb
class Visitor::QuestionsController < ApplicationController

  def new
    @panel = Panel.find(params[:panel_id])
    @question = VisitorQuestion.new
  end

  def create
    @panel = Panel.find(question_params[:panel_id])
    @question = @panel.questions.create!(
      type: 'VisitorQuestion',
      content: question_params[:content],
      author: 'visitor'
    )

    VisitorQuestionsRelayJob.perform_later(@panel, @question)
    GlobalVisitorQuestionsRelayJob.perform_later(@panel, @question)

    redirect_to visitor_panels_url, notice: "Die Frage wurde gespeichert."
  end

private
  def question_params
    params.permit(:panel_id, :content)
  end

end

app/views/operator/questions/new.html.erb
  <% page_title 'Veranstalter - Frage eingeben' %>

  <%= link_to('', operator_panels_path, class: 'close-button') %>

  <div class="app app-main-container new-question">
    <%= form_tag(operator_panel_questions_path(@panel), class: 'form-horizontal push-5-t question-form') do %>
    <%= hidden_field_tag 'panel_id', @panel.id %>

    <div class="row">
      <div class="col-md-10 col-md-offset-1">
        <h1 class="push-50">Geben Sie Ihre Frage für das <%= @panel.title %> ein.</h1>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-md-8 col-md-offset-2">
        <div class="speech-bubble">
          <div class="form-group">
            <label class="col-xs-12" for="visitor-message">Bitte geben Sie Ihre Frage ein.</label>

            <div class="col-xs-12">
              <textarea class="form-control" id="visitor-message" name="content" placeholder="Ihre Frage..." maxlength="280"></textarea>
              <span class="badge badge-letter-count push-10-t"><h5 id="count_character"></h5></span>
            </div>
          </div>
        </div><!-- .speech-bubble -->
      </div><!-- .col -->
    </div><!-- .row -->

    <div class="row">
      <div class="col-md-10 col-md-offset-1 push-50-t">
        <%= link_to operator_panels_path, class: 'btn btn-danger btn-with-icon push-10-r reset-button' do %>
          <div class="ht-40 justify-content-between">
            <span class="pd-x-15">Abbrechen</span>
            <span class="icon wd-40"><i class="fa fa-times-circle"></i></span>
          </div>
        <%- end -%>

        <%= link_to '#', class: 'btn btn-success btn-with-icon push-10-l submit-button' do %>
          <div class="ht-40 justify-content-between">
            <span class="pd-x-15">Frage abschicken</span>
            <span class="icon wd-40"><i class="fa fa-share-square"></i></span>
          </div>
        <%- end -%>
      </div>
    </div>

    <% end -%>
  </div>

  <script>

    $( document ).ready(function() {

      var text_max = $('#visitor-message').attr('maxlength') || 100;
      $('#count_character').html(text_max + ' Zeichen verbleibend');

      $('#visitor-message').keyup(function() {
        var text_length = $('#visitor-message').val().length;
        var text_remaining = text_max - text_length;

        if (text_remaining >= 0) {
          $('#count_character').html(text_remaining + ' Zeichen verbleibend');
        }
      });

      $('.close-button, .reset-button').on('click', function(e) {
        var formChanged = $('#visitor-message').val().length > 0,
            message = 'Wirklich abbrechen OHNE zu speichern?';

        if (formChanged) {
          return confirm(message);
        }
      });

      $('.question-form .submit-button').on('click', function(e) {
        e.preventDefault();
        if($('#visitor-message').val().length > 0) {
          Rails.disableElement(this);
          $(this).closest('form').submit();
        }
      });
    });

</script>